# .github/workflows/deploy-backend-to-azure.yml
# Đặt file này trong thư mục .github/workflows/ của repository

name: Build and Deploy Backend to Azure Web App

on:
  # Kích hoạt workflow mỗi khi có push lên branch `master`
  push:
    branches:
      - master
    # Chỉ chạy workflow nếu có thay đổi trong thư mục backend hoặc chính file workflow này
    paths:
      - "mln122_backend/**"
      - ".github/workflows/deploy-backend-to-azure.yml"

  # Cho phép chạy workflow thủ công từ tab Actions trên GitHub
  workflow_dispatch:

jobs:
  build:
    # --- GIAI ĐOẠN BUILD ---
    # Mục tiêu: Cài đặt, build ứng dụng và tạo một gói artifact sẵn sàng cho production.
    runs-on: ubuntu-latest

    steps:
      - name: "1. Checkout Repository"
        # Tải mã nguồn từ repository về máy ảo của GitHub Actions
        uses: actions/checkout@v4

      - name: "2. Set up Node.js and Yarn"
        # Cài đặt phiên bản Node.js và kích hoạt cache cho yarn để tăng tốc các lần chạy sau
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "yarn"
          cache-dependency-path: mln122_backend/yarn.lock

      - name: "3. Install All Dependencies and Build"
        # Di chuyển vào thư mục backend, cài đặt tất cả các gói (bao gồm devDependencies)
        # và chạy lệnh build để biên dịch TypeScript ra JavaScript.
        working-directory: ./mln122_backend
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: "4. Prune Dev Dependencies"
        # Sau khi build xong, chạy lại yarn install với cờ --production
        # để xóa các gói dev không cần thiết, giúp gói deploy nhẹ hơn.
        working-directory: ./mln122_backend
        run: yarn install --production --frozen-lockfile

      - name: "5. Archive Production Artifact"
        # Đóng gói các thư mục và file cần thiết cho production (dist, node_modules, package.json)
        # và tải nó lên làm một "artifact" để job `deploy` có thể sử dụng.
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact
          path: |
            mln122_backend/dist
            mln122_backend/node_modules
            mln122_backend/package.json

  deploy:
    # --- GIAI ĐOẠN DEPLOY ---
    # Mục tiêu: Lấy artifact đã build và triển khai nó lên Azure Web App.
    runs-on: ubuntu-latest
    needs: build # Job này chỉ chạy sau khi job `build` hoàn thành thành công
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: "1. Download Artifact from Build Job"
        # Tải gói artifact đã được tạo ở job `build` về máy ảo.
        uses: actions/download-artifact@v4
        with:
          name: node-app-artifact

      - name: "2. Deploy to Azure Web App"
        # Sử dụng action của Azure để deploy.
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "MLN122" # Tên Web App của bạn trên Azure
          slot-name: "Production"
          package: . # Deploy nội dung của artifact đã tải về
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Rất quan trọng: Secret chứa publish profile
